
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100
  
arm_controller:
  joint_1_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_a1
    pid : {p : 100, i : 0.0, d : 10}

  joint_2_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_a2
    pid : {p : 100, i : 0.0, d : 10}

  joint_3_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_a3
    pid : {p : 100, i : 0.0, d : 10}

  joint_4_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_a4
    pid : {p : 100, i : 0.0, d : 10}

  joint_5_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_a5
    pid : {p : 100, i : 0.0, d : 10}

  joint_6_pos_controller:
    type : position_controllers/JointPositionController
    joint : joint_a6
    pid : {p : 100, i : 0.0, d : 10}
